name: Test and Lint

on: [push, pull_request]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn eslint --ext .js,.vue .

      - name: Run Prettier
        run: yarn prettier --check .

      - name: Run tests
        run: yarn jest --passWithNoTests
